### ISSUE TITLE
Cycada non-copyrighted source code

### ISSUE THREAD

**Issue by upintheairsheep2** [afrojer/env-setup#2]
Can you open source Cider/Cycada but **without** all those frameworks, apps, and libraries copied from iOS? Only open source the code the team worked on. This will pave the way for a future Cider reboot. There are tools like Corellum that allow the reverse engineering to be MUCH faster. What version of iOS did you copy the frameworks and libraries from? If you no longer have access or lost the code, reply that you lost it. Please add documentation on how to install the Cycada, how to extract the libraries from iOS, how to install them on Cider, and how to install an .ipa file. If you still have those ipa sample files, please upload them to the internet archive for preservation of the older apps. Also, Why did you delete your Facebook and Instagram account?

**Comment by upintheairsheep2** [comment]
Oh i got blocked

**Comment by afrojer** [comment]
There is no code change or feature requested here, and the prose is not relevant to this project or repo. Closing.

**Comment by upintheairsheep** [comment]
> There is no code change or feature requested here, and the prose is not relevant to this project or repo. Closing.
Currently this is the only method to contact you.
Do you still have Cycada or any code related or the Nexus 7 with the prototype or is it at Columbia? Just say yes or no. I’d love to see more footage.

**Comment by Jadoo4QFan** [comment]
Hello Mr. Andreus, I'm sorry for bugging you about Cycada. I respect that you are no longer part of the ill-fated project. I respect your job and your family, however, you probably no longer have any control over the project. If you choose to accept this apology, you could try doing more work on the project if you'd like, and if you are really generous, you could simply release a more in-depth video about Cycada to YouTube, testing all the apps on the paper and playing around with the device. It may still be possible to release the working source code prototype of Cycada on GitHub, however, changed dramatically to only include Cycada code and no proprietary iOS code, only making .diff files of the modified iOS code, and then the community may port Cycada other places, however, if you want to respect Apple's EULA, make Cycada a macOS app which runs Android with Cycada in a VM for legacy retro 32-bit iOS apps. If you are lucky, the FOSS community will try adding more features and fixing compatibility for many apps.  I'm not forcing you to release Cycada, and you don't have to publish a new video, but I learned in life that you should not be greedy, nor should you ever give up on your hopes and dreams. Losing hope will only make you depressed and a failure and never reach your dreams. That's why I contacted everyone. I have something called "hope" in my heart. I am a pure Muslim and plan to pray all my daily prayers in respect for God. I found in a paper about how these same human factors that I have done to contact you and your colleagues created Cycada altogether. Releasing Cycada should put all of us down in the history books when people execute native iOS software in an Android emulator and remember all of us. My real name is Kayvon Kamyar, however only mention myself in the credits as Kayvon K. as I would prefer to be private for now. I am not forcing you to do it, however, I have been chasing this dream for a while. The only response I've ever gotten was from Mr. Dall saying that due to the code changes being proprietary it was a no, and if it did you would need some work, however, I remembered about .diff files, solving copyright issues with modified code since it was released. If you no longer have access, use your university email to tell Nieh about this and diff files and get the software released if the code wasn't deleted. I'm not forcing you, but denial will only break my heart. It would also be a great time to release the code of some other unreleased projects with less "iffy" copyright issues like M2 and Flux, even a sorry gift if Cycada never gets released. Getting no response has always made me lose hope, making me feel insignificant in this world, only adding to times I feel hopeless and worthless. May God be with us and protect us.
